from settings import ROWS, COLS

MODEL_FILE_NAME = "deep_model.pt"
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

FEAT_WALLS = 0
FEAT_CRATES = 1
FEAT_COINS = 2
FEAT_BOMBS = 3
FEAT_OTHERS = 4

FEATURE_SHAPE = (5, 2 * ROWS - 3, 2 * COLS - 3)
FEATURE_SIZE = FEATURE_SHAPE[0] * FEATURE_SHAPE[1] * FEATURE_SHAPE[2]