from settings import ROWS, COLS

MODEL_FILE_NAME = "linear_model.pt"
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

FEAT_WALLS = 0
FEAT_CRATES = 1
FEAT_COINS = 2
FEAT_BOMBS = 3
FEAT_OTHERS = 4

FEATURE_SHAPE_OLD = (5, 2 * ROWS - 3, 2 * COLS - 3)
FEATURE_SIZE_OLD = FEATURE_SHAPE_OLD[0] * FEATURE_SHAPE_OLD[1] * FEATURE_SHAPE_OLD[2]

FEATURE_SIZE = 4*len(ACTIONS) + 2